cockpit.locale({
  '': {
    'plural-forms': (n) => n != 1,
    'language': 'ka',
    'language-direction': 'ltr',
  },
  '"$0" exists, not overwriting with paste.': [null, '"$0" არსებობს. ჩასმით მას თავზე არ გადაეწერება.'],
  '$0 item': [null, '$0 ელემენტი', '$0 ელემენტი'],
  '$0 item is hidden': [null, '$0 ელემენტი დამალულია', '$0 ელემენტი დამალულია'],
  '$0 permissions': [null, '$0 წვდომა'],
  '($0 hidden)': [null, '($0 დამალული)', '($0 დამალული)'],
  'A file with the same name already exists in "$0". Replacing it will overwrite its content.': [
    null,
    'ფაილი იგივე სახელით "$0"-ში უკვე არსებობს. მისი ჩანაცვლება მის შემცველობას თავზე გადააწერს.',
  ],
  'A-Z': [null, 'A-Z'],
  'Access': [null, 'წვდომა'],
  'Activate selected item, enter directory': [null, 'მონიშნული ელემენტის გააქტიურება საქაღალდეში შესვლა'],
  'Add bookmark': [null, 'სანიშნეს დამატება'],
  'Apply this action to all conflicting files': [null, 'ამ ქმედების გადატარება ყველა კონფლიქტურ ფაილზე'],
  'Block device': [null, 'ბლოკური მოწყობილობა'],
  'Bookmarks': [null, 'სანიშნეები'],
  'Cancel': [null, 'გაუქმება'],
  'Cancel upload of $0': [null, '$0-ის ატვირთვის შეწყვეტა'],
  'Cancelled': [null, 'გაუქმებულია'],
  'Cancelled upload of $0': [null, '$0-ის ატვირთვა შეწყდა'],
  'Change': [null, 'შეცვლა'],
  'Character device': [null, 'სიმბოლური მოწყობილობა'],
  'Clear filter': [null, 'ფილტრის გასუფთავება'],
  'Close': [null, 'დახურვა'],
  'Cockpit Files': [null, 'Cockpit Files'],
  'Copy': [null, 'კოპირება'],
  'Copy selected file or directory': [null, 'მონიშნული ფაილის ან საქაღალდის კოპირება'],
  'Create': [null, 'შექმნა'],
  'Create directory': [null, 'საქაღალდის შექმნა'],
  'Create new directory': [null, 'ახალი საქაღალდის შექმნა'],
  'Delete': [null, 'წაშლა'],
  'Delete $0 items?': [null, 'წავშალო $0 ელემენტი?'],
  'Delete $0?': [null, 'წავშალო $0?'],
  'Delete directory $0?': [null, 'წავშალო საქაღალდე $0?'],
  'Delete file $0?': [null, 'წავშალო ფაილი $0?'],
  'Delete link $0?': [null, 'წავშალო ბმული $0?'],
  'Directories & files': [null, 'საქაღალდეები და ფაილები'],
  'Directory': [null, 'საქაღალდე'],
  'Directory is empty': [null, 'საქაღალდე ცარიელია'],
  'Directory name': [null, 'საქაღალდის სახელი'],
  'Directory name cannot be empty.': [null, 'საქაღალდის სახელი ცარიელი ვერ იქნება.'],
  'Directory name cannot include a /.': [null, "საქაღალდის სახელი, არ შეიძლება, სიმბოლოს '/' შეიცავდეს."],
  'Directory name too long.': [null, 'საქაღალდის სახელი ძალიან გრძელია.'],
  'Directory owner': [null, 'საქაღალდის მფლობელი'],
  'Directory with the same name exists': [null, 'საქაღალდე იგივე სახელით უკვე არსებობს'],
  'Display as a grid': [null, 'ბადის სახით ჩვენება'],
  'Display as a list': [null, 'სიის სახით ჩვენება'],
  'Download': [null, 'გადმოწერა'],
  'Edit $0': [null, '$0-ის ჩასწორება'],
  'Edit path': [null, 'ბილიკის ჩასწორება'],
  'Edit permissions': [null, 'წვდომების ჩასწორება'],
  'Editing': [null, 'ჩასწორება'],
  'Execute-only': [null, 'მხოლოდ-გამშვები'],
  'File exists': [null, 'ფაილი არსებობს'],
  'Filename is the same as original name': [null, 'ფაილის სახელი იგივეა, რაც საწყისი სახელი'],
  'Filesystem': [null, 'ფაილური სისტემა'],
  'Filter directory': [null, 'საქაღალდის ფილტრი'],
  'First modified': [null, 'პირველი ცვლილება'],
  'Force delete $0': [null, '$0-ის ნაძალადევი წაშლა'],
  'Force delete $0 items': [null, '$0 ელემენტის ნაძალადევი წაშლა'],
  'Force delete directory $0?': [null, 'წავშალო ძალით საქაღალდე $0?'],
  'Force delete file $0?': [null, 'წავშალო ძალით ფაილი $0?'],
  'Force delete link $0?': [null, 'წავშალო ძალით ბმული $0?'],
  'Go back': [null, 'უკან გადასვლა'],
  'Go forward': [null, 'წინ გადასვლა'],
  'Go up a directory': [null, 'ზემო საქაღალდეზე გადასვლა'],
  'Group': [null, 'ჯგუფი'],
  'Group access': [null, 'ჯგუფის წვდომა'],
  'Group permissions': [null, 'ჯგუფის წვდომები'],
  'Hide hidden items': [null, 'დამალული ელემენტების დამალვა'],
  'Home': [null, 'საწყისი'],
  'Ignore': [null, 'დაიგნორება'],
  'Keep original': [null, 'ორიგინალის შენარჩუნება'],
  'Keyboard shortcuts': [null, 'კლავიატურის მალსახმობები'],
  'Largest size': [null, 'უდიდესი ზომა'],
  'Last modified': [null, 'ბოლო ცვლილება'],
  'Least permissive': [null, 'ყველაზე ნაკლები დაშვებით'],
  'Modified': [null, 'შეცვლილია'],
  'Most permissive': [null, 'ყველაზე მეტი დაშვებით'],
  'Name': [null, 'სახელი'],
  'Name cannot be empty.': [null, 'სახელი არ შეიძლება იყოს ცარიელი.'],
  'Name cannot include a /.': [null, "სახელი, არ შეიძლება, სიმბოლოს '/' შეიცავდეს."],
  'Name too long.': [null, 'სახელი ძალიან გრძელია.'],
  'Named pipe': [null, 'სახელიანი ფაიფი'],
  'Navigation': [null, 'ნავიგაცია'],
  'New file': [null, 'ახალი ფაილი'],
  'New filename': [null, 'ახალი ფაილის სახელი'],
  'New name': [null, 'ახალი სახელი'],
  'No access': [null, 'წვდომის გარეშე'],
  'No matching results': [null, 'პასუხები არაა'],
  'None': [null, 'არაფერი'],
  'Open text file': [null, 'ტექსტური ფაილის გახსნა'],
  'Original file on server': [null, 'ორიგინალი ფაილი სერვერზე'],
  'Other permissions': [null, 'სხვა წვდომები'],
  'Others': [null, 'სხვები'],
  'Others access': [null, 'სხვების წვდომა'],
  'Overwrite': [null, 'გადაწერა'],
  'Owner': [null, 'მფლობელი'],
  'Owner access': [null, 'მფლობელის წვდომა'],
  'Owner ascending': [null, 'მფლობელი აღმავალი'],
  'Owner descending': [null, 'მფლობელი დაღმავალი'],
  'Owner permissions': [null, 'მფლობელის წვდომები'],
  'Ownership': [null, 'მფლობელობა'],
  'Paste': [null, 'ჩასმა'],
  'Paste file or directory': [null, 'ფაილის ან საქაღალდის ჩასმა'],
  'Pasting failed': [null, 'ჩასმა ჩავარდა'],
  'Permissions': [null, 'წვდომები'],
  'Read and execute': [null, 'წაკითხვა და გაშვება'],
  'Read and write': [null, 'წაკითხვა და ჩაწერა'],
  'Read, write, and execute': [null, 'წაკითხვა, ჩაწერა და გაშვება'],
  'Read-only': [null, 'მხოლოდ-წასაკითხად'],
  'Regular file': [null, 'ჩვეულებრივი ფაილი'],
  'Reload': [null, 'თავიდან ჩატვირთვა'],
  'Remove current directory': [null, 'მიმდინარე საქაღალდის წაშლა'],
  'Rename': [null, 'გადარქმევა'],
  'Rename $0?': [null, 'გადავარქვა სახელი ფაილს $0?'],
  'Rename selected file or directory': [null, 'მონიშნული ფაილის ან საქაღალდის სახელის გადარქმევა'],
  'Replace': [null, 'ჩანაცვლება'],
  'Replace file $0?': [null, 'ჩავანაცვლო ფაილი $0?'],
  'Save': [null, 'შენახვა'],
  'Security context': [null, 'უსაფრთხოების კონტექსტი'],
  'Select all': [null, 'ყველას მონიშვნა'],
  'Set executable as program': [null, 'პროგრამის გაშვებადად დაყენება'],
  'Show hidden items': [null, 'დამალული ელემენტების ჩვენება'],
  'Show keyboard shortcuts': [null, 'კლავიატურის მალსახმობების ჩვენება'],
  'Size': [null, 'ზომა'],
  'Smallest size': [null, 'უმცირესი ზომა'],
  'Socket': [null, 'სოკეტი'],
  'Sort': [null, 'დალაგება'],
  'Successfully uploaded file(s)': [null, 'ფაილები წარმატებით აიტვირთა'],
  'Symbolic link': [null, 'სიმბმული'],
  'The existing file changed unexpectedly': [null, 'არსებული ფაილი წარმატებით შეიცვალა'],
  'The file has been removed on disk': [null, 'ფაილი წაიშალა დისკიდან'],
  'The file has changed on disk': [null, 'ფაილი შეიცვალა დისკზე'],
  'Unable to create bookmark directory': [null, 'სანიშნეების საქაღალდის შექმნა შეუძლებელია'],
  'Unable to save bookmark file': [null, 'სანიშნეს ფაილის შენახვა შეუძლებელია'],
  'Upload': [null, 'ატვირთვა'],
  'Upload $0% completed': [null, 'ატვირთვის $0% დასრულდა'],
  'Upload complete': [null, 'ატვირთვა დასრულებულია'],
  'Upload error': [null, 'ატვირთვის შეცდომა'],
  'Uploads': [null, 'ატვირთვები'],
  'View $0': [null, '$0-ის ნახვა'],
  'Write and execute': [null, 'ჩაწერა და შესრულება'],
  'Write-only': [null, 'მხოლოდ-ჩაწერადი'],
  'Z-A': [null, 'Z-A'],
});
