cockpit.locale({
  '': {
    'plural-forms': (n) => 0,
    'language': 'zh_TW',
    'language-direction': 'ltr',
  },
  '"$0" exists, not overwriting with paste.': [null, '"$0" 已存在，將不會貼上以免遭覆寫。'],
  '$0 item': [null, '$0 個項目'],
  '$0 item is hidden': [null, '$0 個已隱藏的項目'],
  '$0 permissions': [null, '$0 的權限'],
  '($0 hidden)': [null, '(已隱藏 $0 個)'],
  'A file with the same name already exists in "$0". Replacing it will overwrite its content.': [null, '一個相同名稱的檔案已於 "$0" 存在。 若將其取代將覆寫其內容。'],
  'A-Z': [null, '由 A 到 Z'],
  'Access': [null, '存取權限'],
  'Activate selected item, enter directory': [null, '觸發所選擇的項目，進入目錄'],
  'Add bookmark': [null, '新增書籤'],
  'Apply this action to all conflicting files': [null, '套用此動作至所有發生衝突的檔案'],
  'Block device': [null, '區塊裝置'],
  'Bookmarks': [null, '書籤'],
  'Cancel': [null, '取消'],
  'Cancel upload of $0': [null, '取消上傳 $0'],
  'Cancelled': [null, '已取消'],
  'Cancelled upload of $0': [null, '已取消上傳 $0'],
  'Change': [null, '變更'],
  'Character device': [null, '字元裝置'],
  'Clear filter': [null, '清除篩選器'],
  'Close': [null, '關閉'],
  'Cockpit Files': [null, 'Cockpit Files'],
  'Copy': [null, '複製'],
  'Copy selected file or directory': [null, '複製已選擇的檔案或目錄'],
  'Create': [null, '建立'],
  'Create directory': [null, '建立目錄'],
  'Create new directory': [null, '建立新目錄'],
  'Delete': [null, '刪除'],
  'Delete $0 items?': [null, '刪除 $0 個項目？'],
  'Delete $0?': [null, '刪除 $0 ？'],
  'Delete directory $0?': [null, '刪除目錄 $0 ？'],
  'Delete file $0?': [null, '刪除檔案 $0 ？'],
  'Delete link $0?': [null, '刪除連結 $0 ？'],
  'Directories & files': [null, '目錄與檔案'],
  'Directory': [null, '目錄'],
  'Directory is empty': [null, '目錄是空的'],
  'Directory name': [null, '目錄名稱'],
  'Directory name cannot be empty.': [null, '目錄名稱不能是空值。'],
  'Directory name cannot include a /.': [null, '目錄名稱不能包含 / 。'],
  'Directory name too long.': [null, '目錄名稱太長。'],
  'Directory owner': [null, '目錄擁有者'],
  'Directory with the same name exists': [null, '相同名稱的目錄已存在'],
  'Display as a grid': [null, '以網格顯示'],
  'Display as a list': [null, '以清單顯示'],
  'Download': [null, '下載'],
  'Edit $0': [null, '編輯 $0'],
  'Edit path': [null, '編輯路徑'],
  'Edit permissions': [null, '編輯權限'],
  'Editing': [null, '正在編輯'],
  'Execute-only': [null, '只能執行'],
  'File exists': [null, '檔案已存在'],
  'Filename is the same as original name': [null, '檔案名稱與原本相同'],
  'Filesystem': [null, '檔案系統'],
  'Filter directory': [null, '篩選目錄'],
  'First modified': [null, '初次修改於'],
  'Force delete $0': [null, '強制刪除 $0'],
  'Force delete $0 items': [null, '強制刪除 $0 個項目'],
  'Force delete directory $0?': [null, '強制刪除目錄 $0 ？'],
  'Force delete file $0?': [null, '強制刪除檔案 $0 ？'],
  'Force delete link $0?': [null, '強制刪除連結 $0 ？'],
  'Go back': [null, '返回'],
  'Go forward': [null, '前進'],
  'Go up a directory': [null, '回上一層目錄'],
  'Group': [null, '群組'],
  'Group access': [null, '群組存取權限'],
  'Group permissions': [null, '群組權限'],
  'Hide hidden items': [null, '不顯示隱藏的項目'],
  'Home': [null, '家目錄'],
  'Ignore': [null, '忽略'],
  'Keep original': [null, '保留原本的'],
  'Keyboard shortcuts': [null, '鍵盤快速鍵'],
  'Largest size': [null, '大小最大'],
  'Last modified': [null, '最後修改於'],
  'Least permissive': [null, '最不寬鬆的權限'],
  'Modified': [null, '被修改'],
  'Most permissive': [null, '最寬鬆的權限'],
  'Name': [null, '名稱'],
  'Name cannot be empty.': [null, '名稱不能為空值。'],
  'Name cannot include a /.': [null, '名稱不能包含 / 。'],
  'Name too long.': [null, '名稱太長。'],
  'Named pipe': [null, 'Named pipe'],
  'Navigation': [null, '瀏覽'],
  'New file': [null, '新的檔案'],
  'New filename': [null, '新檔案名稱'],
  'New name': [null, '新名稱'],
  'No access': [null, '無存取權限'],
  'No matching results': [null, '沒有找到相符的結果'],
  'None': [null, '無'],
  'Open text file': [null, '開啟文字檔案'],
  'Original file on server': [null, '伺服器上原有的檔案'],
  'Other permissions': [null, '其他權限'],
  'Others': [null, '其他人'],
  'Others access': [null, '其他人的存取權限'],
  'Overwrite': [null, '覆寫'],
  'Owner': [null, '擁有者'],
  'Owner access': [null, '擁有者存取權限'],
  'Owner ascending': [null, '擁有者遞增排序'],
  'Owner descending': [null, '擁有者遞減排序'],
  'Owner permissions': [null, '擁有者權限'],
  'Ownership': [null, '所有權'],
  'Paste': [null, '貼上'],
  'Paste file or directory': [null, '貼上檔案或目錄'],
  'Pasting failed': [null, '貼上失敗'],
  'Permissions': [null, '權限'],
  'Read and execute': [null, '讀取與執行'],
  'Read and write': [null, '讀取與寫入'],
  'Read, write, and execute': [null, '讀取、寫入與執行'],
  'Read-only': [null, '只能讀取'],
  'Regular file': [null, '一般檔案'],
  'Reload': [null, '重新載入'],
  'Remove current directory': [null, '移除目前的目錄'],
  'Rename': [null, '重新命名'],
  'Rename $0?': [null, '將 $0 重新命名？'],
  'Rename selected file or directory': [null, '重新命名已選擇的檔案或目錄'],
  'Replace': [null, '取代'],
  'Replace file $0?': [null, '取代檔案 $0 ？'],
  'Save': [null, '儲存'],
  'Security context': [null, '安全性 context'],
  'Select all': [null, '全選'],
  'Set executable as program': [null, '設定為可執行的程式'],
  'Show hidden items': [null, '顯示隱藏的項目'],
  'Show keyboard shortcuts': [null, '顯示鍵盤快速鍵'],
  'Size': [null, '大小'],
  'Smallest size': [null, '大小最小'],
  'Socket': [null, 'Socket'],
  'Sort': [null, '排序'],
  'Successfully uploaded file(s)': [null, '檔案上傳成功'],
  'Symbolic link': [null, '符號連結'],
  'The existing file changed unexpectedly': [null, '既存的檔案有意料外的變更'],
  'The file has been removed on disk': [null, '該檔案已被從磁碟上移除'],
  'The file has changed on disk': [null, '該檔案已在磁碟上被變更'],
  'Unable to create bookmark directory': [null, '無法建立書籤的存放目錄'],
  'Unable to save bookmark file': [null, '無法儲存書籤的存放檔案'],
  'Upload': [null, '上傳'],
  'Upload $0% completed': [null, '上傳 $0% 完成'],
  'Upload complete': [null, '上傳已完成'],
  'Upload error': [null, '上傳失敗'],
  'Uploads': [null, '上傳項目'],
  'View $0': [null, '檢視 $0'],
  'Write and execute': [null, '寫入與執行'],
  'Write-only': [null, '只能寫入'],
  'Z-A': [null, '由 Z 到 A'],
});
