/**
 * @file src/auth.ts
 * @description This file contains the auth functions.
 * @author Luca Liguori
 * @created 2024-05-01
 * @version 1.1.0
 * @license Apache-2.0
 *
 * Copyright 2024, 2025, 2026 Luca Liguori.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import crypto from 'node:crypto';

export interface AuthParams {
  realm: string; // device_id
  username: string; // admin
  nonce: number | string; // generated by device (legacy: numeric, firmware 2.0.0+: base64 string)
  cnonce: number; // random number
  nc: string; // nonce count
  response: string; // hash <<user>:<realm>:<password>> + ":" + <nonce> + ":" + <nc> + ":" + <cnonce> + ":" + "auth" + ":" + <dummy_method:dummy_uri>
  algorithm: string; // SHA-256
}

/**
 * Parses the Basic Authentication header.
 *
 * @param {string} authHeader - The Basic Authentication header.
 * @returns {Record<string, string>} An object containing the parsed authentication parameters.
 */
export function parseBasicAuthenticateHeader(authHeader: string): Record<string, string> {
  // 'Basic realm="Shelly"'
  const header = authHeader.replace('Basic ', '');
  const authParams: Record<string, string> = {};
  header.split(', ').forEach((param) => {
    const eqIdx = param.indexOf('=');
    if (eqIdx === -1) return;
    const key = param.slice(0, eqIdx).trim();
    const value = param.slice(eqIdx + 1).replace(/"/g, '');
    authParams[key] = value;
  });
  return authParams;
}

/**
 * Parses the Digest Authentication header.
 *
 * @param {string} authHeader - The Digest Authentication header.
 * @returns {Record<string, string>} An object containing the parsed authentication parameters.
 */
export function parseDigestAuthenticateHeader(authHeader: string): Record<string, string> {
  // 'Digest qop="auth", realm="shellyemminig4-d885acef41a8", nonce="AAAAAGoN/xP...==", algorithm=SHA-256'
  const header = authHeader.replace('Digest ', '');
  const authParams: Record<string, string> = {};
  header.split(', ').forEach((param) => {
    const eqIdx = param.indexOf('=');
    if (eqIdx === -1) return;
    const key = param.slice(0, eqIdx).trim();
    const value = param.slice(eqIdx + 1).replace(/"/g, '');
    authParams[key] = value;
  });
  return authParams;
}

/**
 * Creates a Basic Authentication header.
 *
 * @param {string} username - The username for authentication.
 * @param {string} password - The password for authentication.
 * @returns {string} The Base64-encoded Basic Authentication header.
 */
export function createBasicShellyAuth(username: string, password: string): string {
  return Buffer.from(`${username}:${password}`).toString('base64');
}

/**
 * Creates a Digest Authentication object.
 *
 * @param {string} username - The username for authentication.
 * @param {string} password - The password for authentication.
 * @param {number | string} nonce - The nonce value (legacy: numeric, firmware 2.0.0+: base64 string).
 * @param {number} cnonce - The client nonce value.
 * @param {string} realm - The realm value.
 * @param {number} nc - The nonce count. Defaults to 1.
 * @returns {AuthParams} The Digest Authentication object.
 */
export function createDigestShellyAuth(username: string, password: string, nonce: number | string, cnonce: number, realm: string, nc: number = 1): AuthParams {
  const ncHex = nc.toString(16).padStart(8, '0');
  const auth: AuthParams = { realm, username, nonce, cnonce, nc: ncHex, response: '', algorithm: 'SHA-256' };
  const ha1 = crypto.createHash('sha256').update(`admin:${auth.realm}:${password}`).digest('hex');
  const ha2 = crypto.createHash('sha256').update('dummy_method:dummy_uri').digest('hex');
  auth.response = crypto.createHash('sha256').update(`${ha1}:${auth.nonce}:${ncHex}:${cnonce}:auth:${ha2}`).digest('hex');
  return auth;
}

/**
 * Generates a random nonce value.
 *
 * @param {number} min - The minimum value for the nonce.
 * @param {number} max - The maximum value for the nonce.
 * @returns {number} The generated nonce value.
 */
export function generateNonce(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

/**
 * Generates the body options for a Gen 1 request.
 *
 * @param {Record<string, string | number | boolean | object>} [params] - The parameters to include in the body.
 * @returns {string} The URL-encoded body options as a string.
 */
export function getGen1BodyOptions(params?: Record<string, string | number | boolean | object>): string {
  // oxlint-disable-next-line typescript/no-explicit-any typescript/no-unsafe-type-assertion
  return new URLSearchParams(params as any).toString();
}

/*
options: {
  "method":"POST",
  "headers": {
    "Content-Type":"application/json"
  },
  "body": "{
    \"jsonrpc\":\"2.0\",
    \"id\":10,
    \"src\":\"Matterbridge\",
    \"method\":\"Cover.GoToPosition \",
    \"params\":{\"id\":0,\"pos\":90}
  }"
}
*/

/**
 * Generates the body options for a Gen 2 request.
 *
 * @param {string} jsonrpc - The JSON-RPC version.
 * @param {number} id - The request ID.
 * @param {string} src - The source of the request.
 * @param {string} method - The method to call.
 * @param {Record<string, string | number | boolean | object>} [params] - The parameters to include in the body.
 * @param {AuthParams} [auth] - The authentication parameters.
 * @returns {string} The JSON-encoded body options as a string.
 */
export function getGen2BodyOptions(
  jsonrpc: string,
  id: number,
  src: string,
  method: string,
  params?: Record<string, string | number | boolean | object>,
  auth?: AuthParams,
): string {
  const body: Record<string, string | number | boolean | object | AuthParams> = {};
  body.jsonrpc = '2.0';
  body.id = 10;
  body.src = 'Matterbridge';
  body.method = method;
  if (params) body.params = params;
  if (auth) body.auth = auth;
  return JSON.stringify(body);
}
