name: Build, Lint and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # the Node.js versions to build on
        node-version: [18.x, 20.x, 21.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }} 
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install matterbridge
        run: npm -g install matterbridge

      - name: Install dependencies
        run: npm install
  
      - name: Lint the project
        run: npm run lint

      - name: Test the project
        run: npm run test

      - name: Build the project
        run: npm run build

